Repository AndersonTaborga/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#6 Integrar requisitos v1.0
  docs/requisitos.md
Labels: análise

#7 Integrar arquitetura v1.0
  docs/arquitetura.md
Labels: arquitetura

#9 Integrar implementação v1.0
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
Labels: programação

#10 Integrar testes v1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#11 Gerar release v1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações

#14 Gerar release v1.1
  src/jogovelha.py
Labels: operações
